### ISSUE TITLE
T-rex It does not work 

### ISSUE THREAD

**Issue by jiachun97** [JaymZZZZ/claymore-phoenixminer-web-stats#13]
![屏幕截图 2022-01-24 094210](https://user-images.githubusercontent.com/42211037/150709968-c2899392-11fa-4488-826a-8bf89a2df70a.png)

**Comment by JaymZZZZ** [comment]
If you go to https://192.168.0.101:3345/login?password=ZXCzxc885522 does that URL work for you?

**Comment by JaymZZZZ** [comment]
I generated test keys with the password in your config:

Also make sure you set your miner to run with the 
`--api-https --api-read-only --api-bind-http 0.0.0.0:3345 --api-key bwAAAAAAAACo+e51xbfbgN/egInD5E1kSFE9riF5ZayulYnI3/HxYyvlGhI+7YN3oUBgRYoYaUxrwzXrKNCgyuGL/6oErAUyQsIcKNYd6iU=`
flags

You can run it without the api-key flag but I don't recommend that.

**Comment by JaymZZZZ** [comment]
OK, I am going to simplify configuration a little bit. Should make things easier

**Comment by JaymZZZZ** [comment]
Test the latest and let me know how it goes.

**Comment by jiachun97** [comment]
When is_trex=1, the mining machine monitoring interface will disappear. You can carefully look at the server name. The machine with is_trex=1 will not display the interface. 
![屏幕截图 2022-01-24 130245](https://user-images.githubusercontent.com/42211037/150725156-6d2e5e41-9e6e-48e1-8fe7-d4e9b64ac2e7.png)

**Comment by JaymZZZZ** [comment]
It's because you're trying to connect to the claymore miner IP and port (which is an RPC socket, i.e. always open). Because the socket is always open, the app is sitting waiting for a response and will not show the miner until it gets one...but it's never going to get one. Check and make sure you're running Trex API on a different port from the Claymore miner and update the config.

**Comment by jiachun97** [comment]
Configuration is fine 
![屏幕截图 2022-01-24 131215](https://user-images.githubusercontent.com/42211037/150725689-24556a7a-f056-4744-b29d-5cbbb7ad1329.png)
![屏幕截图 2022-01-24 131309](https://user-images.githubusercontent.com/42211037/150725941-b0392193-72f6-45b4-9c19-9d6fa43e51a4.png)
![屏幕截图 2022-01-24 131530](https://user-images.githubusercontent.com/42211037/150725945-349381a8-3b36-4a8b-97e8-0a5c21300ff7.png)

**Comment by JaymZZZZ** [comment]
Can you do me a favor? can you email me the full JSON string from that summary page?

jimok82@gmail.com

**Comment by jiachun97** [comment]
please check email

**Comment by jiachun97** [comment]
T-rex is working fine, bro, have you considered adding password access to the page?

**Comment by JaymZZZZ** [comment]
#14 added. Commit pending
