### ISSUE TITLE
pheonixminer reports watts

### ISSUE THREAD

**Issue by 3ricj** [JaymZZZZ/claymore-phoenixminer-web-stats#2]
Can this tool read the watts so I don't have to enter it (it changes based on .. well, lots of settings, so dynamic would be best.

**Comment by JaymZZZZ** [comment]
Unfortunately, the RPC API currently does not report wattage:

RESPONSE:
{"result": ["9.3 - ETH", "21", "182724;51;0", "30502;30457;30297;30481;30479;30505", "0;0;0", "off;off;off;off;off;off", "53;71;57;67;61;72;55;70;59;71;61;70", "eth-eu1.nanopool.org:9999", "0;0;0;0"]}
"9.3 - ETH"				- miner version.
"21"					- running time, in minutes.
"182724"				- total ETH hashrate in MH/s, number of ETH shares, number of ETH rejected shares.
"30502;30457;30297;30481;30479;30505"	- detailed ETH hashrate for all GPUs.
"0;0;0"					- total DCR hashrate in MH/s, number of DCR shares, number of DCR rejected shares.
"off;off;off;off;off;off"		- detailed DCR hashrate for all GPUs.
"53;71;57;67;61;72;55;70;59;71;61;70"	- Temperature and Fan speed(%) pairs for all GPUs.
"eth-eu1.nanopool.org:9999"		- current mining pool. For dual mode, there will be two pools here.
"0;0;0;0"				- number of ETH invalid shares, number of ETH pool switches, number of DCR invalid shares, number of DCR pool switches.

COMMENTS:
Gets current statistics.

**Comment by JaymZZZZ** [comment]
Without API changes on the mining applications, there is nothing I can do. Sorry.
