### ISSUE TITLE
major performance problem

### ISSUE THREAD

**Issue by 3ricj** [JaymZZZZ/claymore-phoenixminer-web-stats#3]
This is likely a bug in pheonixminder, but one you should be aware of. 

When running this code on high performance miners (eg: 3090 cards at 120mh), running this service with default settings makes the performance of the miner drop to 30-40mh.  This is a major problem.. :(

**Comment by JaymZZZZ** [comment]
Which version of Phoenixminer are you using and what are your settings? The web-stats script should not be affecting this in any ways, and I have been running my 3090 as a test with 106-110MH without issue. I think you might be over-stressing your GPU and having it throttle?

**Comment by 3ricj** [comment]
I'm running 5.5b.  I'll send over some logs in a second

**Comment by 3ricj** [comment]
Here's my pheonixminer log:  https://www.dropbox.com/s/eltddqf6ojjlfsf/20210210_220949.txt?dl=0

I ran it all day (I may have checked the web-stats page briefly once during the day), but the machine was otherwise left alone to mine.  At 5:24 I left the page open for about a minute.  You can see the performance drop. 

Here's some additional information:  The performance impact only seems to happen when I check the stats page from the machine mining -- (locally on it's own display).  If I access the web-stats from other systems it doesn't have this effect. 

I'm using chrome on windows 10.  
My refresh_interval I set to 60 seconds.  

It might be from the animated gifs or something? 

I'll keep poking at this. 
Best, 
-3ric

**Comment by 3ricj** [comment]
(My GPU is undervolted and thus doesn't throttle.  It's at about 70% load, no problems.

**Comment by 3ricj** [comment]
Ok, update..  It was the div class="server" stuff that was killing the box.   I'm not sure what's going on with all of the webkit-animation stuff but it looks like it's stuck in some loop which is trashing the box.  Commenting it out fixed it.

**Comment by JaymZZZZ** [comment]
Are you running the page/browser on the same computer you are mining?
