### ISSUE TITLE
miner window shows php code instead of actual calculations

### ISSUE THREAD

**Issue by bisser** [JaymZZZZ/claymore-phoenixminer-web-stats#4]
I am not really a php person and perhaps this is fixable with a small syntax change? 

below is my config in the conf.php file and a screenshot of the miner report:

	'evil2' => [
		'hostname' => "192.168.7.66",
		'port' => 3333,
		'password' => null,
		'power_usage' => 380,
		'power_cost' => 0.12,
		'pool_fee' => 1,
	]

<img width="360" alt="php_issue" src="https://user-images.githubusercontent.com/4623457/108724084-efdbd000-74f2-11eb-96d2-168da9d15d7c.PNG">

**Comment by bisser** [comment]
one more thing - it works with only 2 rigs, is that the maximum? If I add more than 2, it stops working, not showing anything.

**Comment by JaymZZZZ** [comment]
Looks to be an issue with php short tags, so I replaced them with normal tags now. Please re-download and try it and let me know. It should work with any number of rigs but I think the short tags were causing an issue as well. If it continues, please reopen the issue. Thanks.
