### ISSUE TITLE
still works with only 2 rigs only

### ISSUE THREAD

**Issue by bisser** [JaymZZZZ/claymore-phoenixminer-web-stats#5]
The other issue is fixed and thank you for that! But as soon as I add a 3rd rig, I get an http error 500

**Comment by JaymZZZZ** [comment]
Can you post/attach a copy of your config please? (please change the passwords if you do)

**Comment by bisser** [comment]
Here you go
[conf.zip](https://github.com/JaymZZZZ/claymore-phoenixminer-web-stats/files/6023459/conf.zip)

**Comment by JaymZZZZ** [comment]
you are missing a comma in your config file, at the end of the second node right before your entry for the third node,

**Comment by bisser** [comment]
that worked, thank you so much!
