### ISSUE TITLE
Doesn't work when one miner doesn't respond

### ISSUE THREAD

**Issue by tony-hinkle** [JaymZZZZ/claymore-phoenixminer-web-stats#6]
I don't really know PHP so I haven't yet been able to figure out how to fix it, but if one miner doesn't respond (I'm monitoring 2 miners) it returns a blank page.

**Comment by ghost** [comment]
Same here. Monitoring 100+ rigs and page not loading if 2 or 3 rigs not responding.

**Comment by JaymZZZZ** [comment]
There are two things that you can do to fix this. The script checks the rigs serially (i.e one after the other) and checking every one takes up to 3 seconds (you can change this in config.php) but if you have more rigs, you can edit the "max_execution_time" in php.ini. The default is usually 30 and you can change it any number of seconds you want it to be set to. I will implement a fix in the code to change max_execution_time as well.
