### ISSUE TITLE
The monitor doesnt show profitability from whattomine and error's in console

### ISSUE THREAD

**Issue by omer-bar** [JaymZZZZ/claymore-phoenixminer-web-stats#7]
1. the monitor doesnt show profitability at all, when debugg turned on it gives:
```
Miner Hashrate
Warning: Attempt to read property "profit" on null in C:\inetpub\wwwroot\index.php on line 229
111.67 MH/s
Warning: Attempt to read property "profit" on null in C:\inetpub\wwwroot\index.php on line 231
```

and at the bottom:

> "profitability":null}

i tried to fix it but i dont know any PHP so im guessing this feature is bugged from the start since anything i tried didnt work(including deleting all the calc.json coins and keeping just ETH, and putting the coin ID myself hardcoded)...

2. there is alot of error's in the console:

> The resource from “https://codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
localhost
Some cookies are misusing the recommended “SameSite“ attribute 9
The resource from “https://codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
localhost
The resource from “https://codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
localhost
Loading failed for the <script> with source “http://production-assets.codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js”. localhost:5:1
The resource from “https://codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
localhost
Loading failed for the <script> with source “http://production-assets.codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js”. localhost:6:1
The resource from “https://codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
localhost
Loading failed for the <script> with source “http://production-assets.codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js”. localhost:7:1
GEThttps://codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico
[HTTP/2 404 Not Found 898ms]
GEThttps://codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico

would be nice to see fixes to this problem's.
if you need any help designing or building a react site for this monitor which can be later deployed as react native to smartphones Message me, i can help with that.

**Comment by JaymZZZZ** [comment]
Codepen stuff is gone now so those references can be removed. Can you paste a copy of your config.php (please change/remove the IP/host and passwords).

In order for profitability to work, you have to provide the power cost and power usage in the config. Otherwise it will not work.

**Comment by omer-bar** [comment]
> $server_list = (object)[
> 	'MainRig' => [
> 		'hostname' => "X.X.X.X",
> 		'port' => XXXX,
> 		'password' => "XXXX",
> 		'power_usage' => 385,
> 		'power_cost' => 0.153,
> 		'pool_fee' => 0.65,
>     ],
>     'SecondaryRig' => [
> 		'hostname' => "X.X.X.X",
> 		'port' => XXXX,
> 		'password' => "XXXX",
> 		'power_usage' => 415,
> 		'power_cost' => 0.153,
> 		'pool_fee' => 0.65,
> 	]
> ];
> 
> //Set the socket wait timeout
> $wait_timeout = 3;
> 
> //Set the GPU Temp yellow and red alert values in Celsius
> $gpu_temp_yellow = 70;
> $gpu_temp_red = 75;
> 
> //Set the GPU Fan yellow and red alert values in Percent of max speed
> $gpu_fan_yellow = 50;
> $gpu_fan_red = 75;
> 
> //Set the page refresh interval
> $refresh_interval = 15;
> 
> //Enable Debug Mode if you are having issues
> $debug_mode = TRUE;
> 
> ?>

**Comment by omer-bar** [comment]
> 
> 
> Codepen stuff is gone now so those references can be removed. Can you paste a copy of your config.php (please change/remove the IP/host and passwords).
> 
> In order for profitability to work, you have to provide the power cost and power usage in the config. Otherwise it will not work.

are you going to fix this problem? im thinking of hiring a fiverr programmer in php to fix it..

**Comment by JaymZZZZ** [comment]
I am pretty sure you're missing the PHP cURL module and whatever prerequisites it needs. If you can create a phpinfo page you can check to make cure curl and php-curl are installed because it will not work without that.

**Comment by omer-bar** [comment]
> 
> 
> I am pretty sure you're missing the PHP cURL module and whatever prerequisites it needs. If you can create a phpinfo page you can check to make cure curl and php-curl are installed because it will not work without that.

thats the thing i have curl and php-curl...
curl is shipped with windows natively for at  least two years now...
`curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL`

and PHP is installed using IIS and the PHP-CURL extension is enabled and working(tested using the PHP-CURL docs)

what i get in the page when debug is on is:

>  53
/ 0 / 0
Miner Hashrate
Warning: Attempt to read property "profit" on null in C:\inetpub\wwwroot\index.php on line 224
97.62 MH/s
Warning: Attempt to read property "profit" on null in C:\inetpub\wwwroot\index.php on line 226

i dont think curl got anything to do with it...

**Comment by omer-bar** [comment]
Also found out the page doesn't reload if one of the miner's is down, and sometimes the page reloads a blank page after a couple of minutes and you need to refresh it one or two times until it shows the page again.

**Comment by JaymZZZZ** [comment]
Copy over the latest index.php and json_parser.class.php and then in your conf.php, enable Debug mode. It should print out the debug data much better now. Please paste the whole debug data section here. Thanks.

**Comment by omer-bar** [comment]
> 
> 
> Copy over the latest index.php and json_parser.class.php and then in your conf.php, enable Debug mode. It should print out the debug data much better now. Please paste the whole debug data section here. Thanks.

> DEBUG MODE
> 
> json_parser Object
> (
>     [server_list] => stdClass Object
>         (
>             [MainRig] => stdClass Object
>                 (
>                     [hostname] => MASKED
>                     [port] => MASKED
>                     [password] => MASKED
>                     [power_usage] => 165
>                     [power_cost] => 0.153
>                     [pool_fee] => 0.65
>                 )
> 
>             [NvidiaRig] => stdClass Object
>                 (
>                     [hostname] => MASKED
>                     [port] => MASKED
>                     [password] => MASKED
>                     [power_usage] => 260
>                     [power_cost] => 0.153
>                     [pool_fee] => 0.65
>                 )
> 
>             [AmdRig] => stdClass Object
>                 (
>                     [hostname] => MASKED
>                     [port] => MASKED
>                     [password] => MASKED
>                     [power_usage] => 260
>                     [power_cost] => 0.153
>                     [pool_fee] => 0.65
>                 )
> 
>         )
> 
>     [miner_status] => stdClass Object
>         (
>             [MainRig] => 1
>             [NvidiaRig] => 1
>             [AmdRig] => 1
>         )
> 
>     [miner_data_results] => stdClass Object
>         (
>             [MainRig] => stdClass Object
>                 (
>                     [version] => PM 5.5c
>                     [coin] => ETH
>                     [uptime] => 0d 0h 23m
>                     [pool] => ssl://eth-de.flexpool.io:5555
>                     [stats] => stdClass Object
>                         (
>                             [hashrate] => 42.63
>                             [shares] => 14
>                             [stale] => 0
>                             [rejected] => 0
>                         )
> 
>                     [card_stats] => Array
>                         (
>                             [0] => stdClass Object
>                                 (
>                                     [hashrate] => 42.63
>                                     [temp] => 50
>                                     [fan] => 100
>                                 )
> 
>                         )
> 
>                     [temp_av] => 50
>                     [profitability] => stdClass Object
>                         (
>                             [debug] => stdClass Object
>                                 (
>                                     [url] => https://whattomine.com/coins/151.json?hr=42.63&p=165&fee=0.65&cost=0.153&hcost=0.0&commit=Calculate
>                                     [curl_info] => stdClass Object
>                                         (
>                                             [url] => https://whattomine.com/coins/151.json?hr=42.63&p=165&fee=0.65&cost=0.153&hcost=0.0&commit=Calculate
>                                             [content_type] => 
>                                             [http_code] => 0
>                                             [header_size] => 0
>                                             [request_size] => 0
>                                             [filetime] => -1
>                                             [ssl_verify_result] => 20
>                                             [redirect_count] => 0
>                                             [total_time] => 0.324518
>                                             [namelookup_time] => 0.001336
>                                             [connect_time] => 0.168394
>                                             [pretransfer_time] => 0
>                                             [size_upload] => 0
>                                             [size_download] => 0
>                                             [speed_download] => 0
>                                             [speed_upload] => 0
>                                             [download_content_length] => -1
>                                             [upload_content_length] => -1
>                                             [starttransfer_time] => 0
>                                             [redirect_time] => 0
>                                             [redirect_url] => 
>                                             [primary_ip] => 172.67.68.82
>                                             [certinfo] => Array
>                                                 (
>                                                 )
> 
>                                             [primary_port] => 443
>                                             [local_ip] => 192.168.50.2
>                                             [local_port] => 58263
>                                             [http_version] => 0
>                                             [protocol] => 2
>                                             [ssl_verifyresult] => 0
>                                             [scheme] => HTTPS
>                                             [appconnect_time_us] => 0
>                                             [connect_time_us] => 168394
>                                             [namelookup_time_us] => 1336
>                                             [pretransfer_time_us] => 0
>                                             [redirect_time_us] => 0
>                                             [starttransfer_time_us] => 0
>                                             [total_time_us] => 324518
>                                         )
> 
>                                 )
> 
>                             [result] => 
>                         )
> 
>                 )
> 
>             [NvidiaRig] => stdClass Object
>                 (
>                     [version] => PM 5.5c
>                     [coin] => ETH
>                     [uptime] => 1d 8h 40m
>                     [pool] => ssl://eth-de.flexpool.io:5555
>                     [stats] => stdClass Object
>                         (
>                             [hashrate] => 98.17
>                             [shares] => 2845
>                             [stale] => 0
>                             [rejected] => 2
>                         )
> 
>                     [card_stats] => Array
>                         (
>                             [0] => stdClass Object
>                                 (
>                                     [hashrate] => 49.08
>                                     [temp] => 60
>                                     [fan] => 100
>                                 )
> 
>                             [1] => stdClass Object
>                                 (
>                                     [hashrate] => 49.09
>                                     [temp] => 50
>                                     [fan] => 100
>                                 )
> 
>                         )
> 
>                     [temp_av] => 55
>                     [profitability] => stdClass Object
>                         (
>                             [debug] => stdClass Object
>                                 (
>                                     [url] => https://whattomine.com/coins/151.json?hr=98.17&p=260&fee=0.65&cost=0.153&hcost=0.0&commit=Calculate
>                                     [curl_info] => stdClass Object
>                                         (
>                                             [url] => https://whattomine.com/coins/151.json?hr=98.17&p=260&fee=0.65&cost=0.153&hcost=0.0&commit=Calculate
>                                             [content_type] => 
>                                             [http_code] => 0
>                                             [header_size] => 0
>                                             [request_size] => 0
>                                             [filetime] => -1
>                                             [ssl_verify_result] => 20
>                                             [redirect_count] => 0
>                                             [total_time] => 0.168046
>                                             [namelookup_time] => 0.0008
>                                             [connect_time] => 0.090918
>                                             [pretransfer_time] => 0
>                                             [size_upload] => 0
>                                             [size_download] => 0
>                                             [speed_download] => 0
>                                             [speed_upload] => 0
>                                             [download_content_length] => -1
>                                             [upload_content_length] => -1
>                                             [starttransfer_time] => 0
>                                             [redirect_time] => 0
>                                             [redirect_url] => 
>                                             [primary_ip] => 172.67.68.82
>                                             [certinfo] => Array
>                                                 (
>                                                 )
> 
>                                             [primary_port] => 443
>                                             [local_ip] => 192.168.50.2
>                                             [local_port] => 58267
>                                             [http_version] => 0
>                                             [protocol] => 2
>                                             [ssl_verifyresult] => 0
>                                             [scheme] => HTTPS
>                                             [appconnect_time_us] => 0
>                                             [connect_time_us] => 90918
>                                             [namelookup_time_us] => 800
>                                             [pretransfer_time_us] => 0
>                                             [redirect_time_us] => 0
>                                             [starttransfer_time_us] => 0
>                                             [total_time_us] => 168046
>                                         )
> 
>                                 )
> 
>                             [result] => 
>                         )
> 
>                 )
> 
>             [AmdRig] => stdClass Object
>                 (
>                     [version] => PM 5.6a
>                     [coin] => ETH
>                     [uptime] => 0d 6h 3m
>                     [pool] => ssl://eth-de.flexpool.io:5555
>                     [stats] => stdClass Object
>                         (
>                             [hashrate] => 180.42
>                             [shares] => 1010
>                             [stale] => 1
>                             [rejected] => 0
>                         )
> 
>                     [card_stats] => Array
>                         (
>                             [0] => stdClass Object
>                                 (
>                                     [hashrate] => 60.89
>                                     [temp] => 40
>                                     [fan] => 100
>                                 )
> 
>                             [1] => stdClass Object
>                                 (
>                                     [hashrate] => 31.49
>                                     [temp] => 55
>                                     [fan] => 100
>                                 )
> 
>                             [2] => stdClass Object
>                                 (
>                                     [hashrate] => 56.01
>                                     [temp] => 42
>                                     [fan] => 100
>                                 )
> 
>                             [3] => stdClass Object
>                                 (
>                                     [hashrate] => 32.03
>                                     [temp] => 51
>                                     [fan] => 100
>                                 )
> 
>                         )
> 
>                     [temp_av] => 47
>                     [profitability] => stdClass Object
>                         (
>                             [debug] => stdClass Object
>                                 (
>                                     [url] => https://whattomine.com/coins/151.json?hr=180.42&p=260&fee=0.65&cost=0.153&hcost=0.0&commit=Calculate
>                                     [curl_info] => stdClass Object
>                                         (
>                                             [url] => https://whattomine.com/coins/151.json?hr=180.42&p=260&fee=0.65&cost=0.153&hcost=0.0&commit=Calculate
>                                             [content_type] => 
>                                             [http_code] => 0
>                                             [header_size] => 0
>                                             [request_size] => 0
>                                             [filetime] => -1
>                                             [ssl_verify_result] => 20
>                                             [redirect_count] => 0
>                                             [total_time] => 0.350457
>                                             [namelookup_time] => 0.002928
>                                             [connect_time] => 0.171793
>                                             [pretransfer_time] => 0
>                                             [size_upload] => 0
>                                             [size_download] => 0
>                                             [speed_download] => 0
>                                             [speed_upload] => 0
>                                             [download_content_length] => -1
>                                             [upload_content_length] => -1
>                                             [starttransfer_time] => 0
>                                             [redirect_time] => 0
>                                             [redirect_url] => 
>                                             [primary_ip] => 172.67.68.82
>                                             [certinfo] => Array
>                                                 (
>                                                 )
> 
>                                             [primary_port] => 443
>                                             [local_ip] => 192.168.50.2
>                                             [local_port] => 58271
>                                             [http_version] => 0
>                                             [protocol] => 2
>                                             [ssl_verifyresult] => 0
>                                             [scheme] => HTTPS
>                                             [appconnect_time_us] => 0
>                                             [connect_time_us] => 171793
>                                             [namelookup_time_us] => 2928
>                                             [pretransfer_time_us] => 0
>                                             [redirect_time_us] => 0
>                                             [starttransfer_time_us] => 0
>                                             [total_time_us] => 350457
>                                         )
> 
>                                 )
> 
>                             [result] => 
>                         )
> 
>                 )
> 
>         )
> 
>     [global_hashrate] => 321.22
>     [miner_count] => 3
>     [wait_timeout] => 3
>     [gpu_temp_yellow] => 60
>     [gpu_temp_red] => 65
>     [gpu_fan_yellow] => 80
>     [gpu_fan_red] => 100
>     [calc_json:json_parser:private] => ./calculators.json
>     [debug] => 1
> )
> Node Count:3
> Execution Time:30

**Comment by JaymZZZZ** [comment]
OK, looks like your version of CURL is having an issue verifying the whattomine API's SSL cert. Fix incoming
