### ISSUE TITLE
Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, stdClass given in D:\php\Apache24\htdocs\index.php:19 Stack trace: #0 {main} thrown in D:\php\Apache24\htdocs\index.php on line 19

### ISSUE THREAD

**Issue by markxing2010** [JaymZZZZ/claymore-phoenixminer-web-stats#8]
Hi, I modified the conf.php file and everything is fine but it throws an error below:
Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, stdClass given in D:\php\Apache24\htdocs\index.php:19 Stack trace: #0 {main} thrown in D:\php\Apache24\htdocs\index.php on line 19

**Comment by JaymZZZZ** [comment]
Which version of PHP are you running?
