### ISSUE TITLE
Global Hashrate there are bugs

### ISSUE THREAD

**Issue by jiachun97** [JaymZZZZ/claymore-phoenixminer-web-stats#9]
Global Hashrate does not match real data 
Setting the alarm color for fan speed and gpu temp does not take effect

**Comment by JaymZZZZ** [comment]
The global hashrate is just the sum of what is being reported by the RPC API's. Would you be able to clarify what you are considering to be "real data"?

As far as the alerts, the app will not alarm if the temperatures and fans are high, it will just change the text color to orange or red.

**Comment by zhangjiachun** [comment]
I'm using teamredmine. 
![ec334b3612e36f4deba50fc2cc96756](https://user-images.githubusercontent.com/42211037/150058319-0c92d0c7-c62b-4835-8aa9-2cee85374c3e.png)
Fan color reminder No matter how much the value is set, it is always red.
![958035be8301d2a7fd895e7002e7abe](https://user-images.githubusercontent.com/42211037/150058374-3f77ce67-ded3-4ae9-80cf-b222d3459f28.png)

**Comment by jiachun97** [comment]
I'm using teamredmine.
![c717793457b7a9aa1775d2f7c3b55af](https://user-images.githubusercontent.com/42211037/150058656-85f15750-7fc1-4d3f-b2bb-37f258a573eb.png)
Fan color reminder No matter how much the value is set, it is always red
![958035be8301d2a7fd895e7002e7abe](https://user-images.githubusercontent.com/42211037/150058720-55f293fb-c1ab-4e45-9224-1ec39e65e2ea.png)

**Comment by jiachun97** [comment]
![631b2c1c3079b81f4dccae79b2b5f73](https://user-images.githubusercontent.com/42211037/150069836-41d2569d-c0e3-40b3-abde-20d77c537e67.png)

**Comment by jiachun97** [comment]
The global hashrate keeps changing even without adding any miners

**Comment by JaymZZZZ** [comment]
OK, I see what you mean re: the fan numbers. Those number are red when the value is above the threshold (i.e. the fans are spinning too fast). I think maybe that should be something that can be changed to alert if they go below

I believe, at the time, the goal was to keep the cards cool enough so that the fans didn't need to spin so fast, but not that I think of it that doesn't make sense. I'll look at the other part too.

**Comment by JaymZZZZ** [comment]
OK should be fixed now. Also added option for high/low thresholds for fan speeds
